source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'TWGNotificationObserver_Tests', :exclusive => true do
  pod 'TWGNotificationObserver', :path => '../'
  pod 'OCMock'
  pod 'Expecta'
end
